### ISSUE TITLE
Hash with the date

### ISSUE THREAD

**Issue by DavidBruant** [iOiurson/6sense#19]
Currently, we only hash the device https://github.com/anthill/6sense/pull/17/files#diff-cb26fbd520e6f38da9f1c6d17eb954a1R36
However, this enables tracking people over time. This shouldn't be possible. Add the date to the thing being hashed. `(new Date()).toISOString().slice(0, 10)`.

**Comment by DavidBruant** [comment]
Maybe add a salt (even hardcoded), it cannot hurt.

**Comment by 4rzael** [comment]
Is a salt created with `Math.random().toString(36).substr(2, 5)` good enough ?

**Comment by DavidBruant** [comment]
> Is a salt created with Math.random().toString(36).substr(2, 5) good enough ?

Blah, no :-p Not as coded right now at least. This makes impossible to recognize a device within a day ;-)
Calling `Math.random` gives a different result each time while the hash function must be deterministic (add a test about that too ;-) ) if we want to know how long a car stayed in the recycling center. Even if at the top of the module it changes the value 
A constant salt can be enough. maybe `"ants"`. The salt just makes sure we cannot be attacked by a generic rainbow table written for mac address + date.
