### ISSUE TITLE
6sense sends about 30 times more data since the move to MQTT and bluetooth

### ISSUE THREAD

**Issue by DavidBruant** [iOiurson/6sense#25]
It's been noticed by @vallettea and @4rzael that we pay 30x more than we used to.
Before, we were sending 30Kb/day. Recently, it's been noticed that sensors can send 500Kb in a few hours.

We need to investigate on the causes.
- [ ] Decide on a recording tool. We can either use [WireShark](https://www.wireshark.org/) or set up a TCP client in Node that will record all incoming messages and their sizes
- [ ] Record what is actually being sent by sensors over a period of time including measurements and investigate the raw data to observe what is being sent.

[MQTT spec](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718013). Might be useful to understand what's going on.

**Comment by 4rzael** [comment]
https://github.com/anthill/6brain/issues/24
